services:
  db:
    container_name: auto_crm_db
    image: postgres:16-alpine
    environment:
    - POSTGRES_USER=auto_crm
    - POSTGRES_DB=auto_crm_local
    - POSTGRES_PASSWORD=auto_crm
    - POSTGRES_HOST_AUTH_MEHTOD=trust
    volumes:
    - ./pg_data/data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    healthcheck:
      test: docker exec backend-test-db-1  bash -c 'psql -U auto_crm -d auto_crm_local -c "SELECT ''hi'';"'  
      interval: 1s
      timeout: 5s
    profiles:
      - live
  
  test-db:
    image: postgres:16-alpine
    environment:
    - POSTGRES_USER=auto_crm
    - POSTGRES_DB=auto_crm_test
    - POSTGRES_PASSWORD=auto_crm
    - POSTGRES_HOST_AUTH_MEHTOD=trust
    volumes:
    - ./pg_data/test_data:/var/lib/postgresql/data
    ports:
    - 5433:5432
    healthcheck:
      test: docker exec backend-test-db-1  bash -c 'psql -U auto_crm -d auto_crm_test -c "SELECT ''hi'';"'  
      interval: 1s
      timeout: 5s
    profiles:
      - test